---
title: Athena
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nativ.yeiko@gmail.com
description: Vous retrouver ici mon projet de dévelloper mon Intélligence articiel
  dans le futur une ia complétement autonome
baseurl: "Athena" # the subpath of your site, e.g. /blog
url: "https://nativyeiko.github.io/Athena/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "Athena"
url: 'https://nativyeiko.github.io/Athena/'
twitter_username: jekyllrb
github_username: Yeiko
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-admin
jekyll_admin:
  hidden_links:
  - posts
  - pages
  - staticfiles
  - datafiles
  - configuration
